// Add your coloring pictures here. Drop the image files in img/ then add one entry each:
//     { name: "Lion", src: "../img/lion.png" },
const COLORING_PICTURES = [
    { name: "Clownfish", src: "../img/clownfish.png" },
    { name: "Turtle", src: "../img/turtle.png" },
    { name: "Flower", src: "../img/flower.png" },
    { name: "Daisy", src: "../img/daisy.png" },
    { name: "Lion Cub", src: "../img/lion-cub.png" },
    { name: "Bear Cub", src: "../img/bear-cub.png" },
    { name: "Lion", src: "../img/lion.png" },
    { name: "Fish", src: "../img/fish.png" },
    { name: "Sun", src: "../img/sun.png" },
    { name: "Cloud", src: "../img/cloud.png" },
    { name: "Rainbow", src: "../img/rainbow.png" },
    { name: "Flower 2", src: "../img/flower2.png" },
    { name: "Butterfly", src: "../img/butterfly.png" },
    { name: "Car", src: "../img/car.png" },
    { name: "Rocket", src: "../img/rocket.png" },
    { name: "Cat", src: "../img/cat.png" },
    { name: "Tree", src: "../img/tree.png" },
    { name: "Apple", src: "../img/apple.png" },
    { name: "Star", src: "../img/star.png" },
    { name: "Duck", src: "../img/duck.png" },
    { name: "Sailboat", src: "../img/sailboat.png" },
    { name: "Airplane", src: "../img/airplane.png" },
    { name: "Ladybug", src: "../img/ladybug.png" },
    { name: "Ice Cream", src: "../img/ice-cream.png" },
    { name: "Helicopter", src: "../img/helicopter.png" },
    { name: "Tractor", src: "../img/tractor.png" }
];
