// Add your coloring pictures here. Drop the image files in img/ then add one entry each:
//     { name: "Lion", src: "../img/lion.png" },
const COLORING_PICTURES = [
    { name: "Clownfish", src: "../img/clownfish.png" },
    { name: "Turtle", src: "../img/turtle.png" },
    { name: "Flower", src: "../img/flower.png" },
    { name: "Daisy", src: "../img/daisy.png" },
    { name: "Lion Cub", src: "../img/lion-cub.png" },
    { name: "Bear Cub", src: "../img/bear-cub.png" },
    { name: "Lion", src: "../img/lion.png" },
    { name: "Fish", src: "../img/fish.png" },
    { name: "Sun", src: "../img/sun.png" },
    { name: "Cloud", src: "../img/cloud.png" },
    { name: "Rainbow", src: "../img/rainbow.png" },
    { name: "Flower 2", src: "../img/flower2.png" },
    { name: "Butterfly", src: "../img/butterfly.png" },
    { name: "Car", src: "../img/car.png" },
    { name: "Rocket", src: "../img/rocket.png" },
    { name: "Cat", src: "../img/cat.png" },
    { name: "Tree", src: "../img/tree.png" },
    { name: "Apple", src: "../img/apple.png" },
    { name: "Star", src: "../img/star.png" },
    { name: "Duck", src: "../img/duck.png" },
    { name: "Sailboat", src: "../img/sailboat.png" },
    { name: "Airplane", src: "../img/airplane.png" },
    { name: "Ladybug", src: "../img/ladybug.png" },
    { name: "Ice Cream", src: "../img/ice-cream.png" },
    { name: "Helicopter", src: "../img/helicopter.png" },
    { name: "Tractor", src: "../img/tractor.png" },
    { name: "Horse", src: "../img/horse.png" },
    { name: "Horse Coloring", src: "../img/horse-coloring.png" },
    { name: "Seahorse", src: "../img/seahorse-coloring.png" },
    { name: "Sheep", src: "../img/sheeps-coloring.png" },
    { name: "Cat Coloring", src: "../img/cat-coloring.png" },
    { name: "Dog Coloring", src: "../img/dog-coloring.png" },
    { name: "Elephant Coloring", src: "../img/elephant-coloring.png" },
    { name: "Pig Coloring", src: "../img/pig-coloring.png" },
    { name: "Rabbit Coloring", src: "../img/rabbit-coloring.png" },
    { name: "Teddy Bears", src: "../img/teddy-bears-coloring.png" },
    { name: "Christmas Kittens", src: "../img/christmas-kittens.png" },
    { name: "Santa Claus", src: "../img/christmas-santa-claus.png" },
    { name: "Christmas Stockings", src: "../img/christmas-stockings.png" },
    { name: "Christmas Teddy Bears", src: "../img/christmas-teddy-bears.png" },
    { name: "Christmas Tree", src: "../img/christmas-tree.png" },
    { name: "Merry Christmas", src: "../img/merry-christmas.png" },
    { name: "Muffin Coloring", src: "../img/muffin-coloring.png" },
    { name: "Breakfast Coloring", src: "../img/breakfast-coloring.png" },
    { name: "Candies Coloring", src: "../img/candies-coloring.png" },
    { name: "Fruit Coloring", src: "../img/fruit-coloring.png" },
    { name: "Ice Cream Coloring", src: "../img/ice-cream-coloring.png" },
    { name: "Lollipop Coloring", src: "../img/lollipop-coloring.png" },
    { name: "Spaghetti Coloring", src: "../img/spaghetti-coloring.png" },
    { name: "Sweets Coloring", src: "../img/sweets-coloring.png" },
    { name: "Vegetable Coloring", src: "../img/vegetable-coloring.png" },
    { name: "Princess Glasses", src: "../img/princess-glasses.png" },
    { name: "Princess Beach", src: "../img/princess-beach.png" },
    { name: "Princess Fox", src: "../img/princess-fox.png" },
    { name: "Princess Coloring 1", src: "../img/princess-coloring-1.png" },
    { name: "Princess Coloring 2", src: "../img/princess-coloring-2.png" },
    { name: "Princess Moon", src: "../img/princess-moon.png" },
    { name: "Princess Coloring 3", src: "../img/princess-coloring-3.png" },
    { name: "Princess Coloring 4", src: "../img/princess-coloring-4.png" },
    { name: "Princess Coloring 5", src: "../img/princess-coloring-5.png" },
    { name: "Airplane Coloring", src: "../img/airplane-coloring.png" },
    { name: "Car Coloring", src: "../img/car-coloring.png" },
    { name: "Helicopter Coloring", src: "../img/helicopter-coloring.png" },
    { name: "Ship Coloring", src: "../img/ship-coloring.png" },
    { name: "Train Coloring", src: "../img/train-coloring.png" },
    { name: "Truck Coloring", src: "../img/truck-coloring.png" },
    { name: "Unicorn Birds", src: "../img/unicorn-birds.png" },
    { name: "Unicorn Walking", src: "../img/unicorn-walking.png" },
    { name: "Unicorn Flower", src: "../img/unicorn-flower.png" },
    { name: "Unicorn Flying", src: "../img/unicorn-flying.png" },
    { name: "Unicorn Friend", src: "../img/unicorn-friend.png" },
    { name: "Unicorn Jumping", src: "../img/unicorn-jumping.png" },
    { name: "Unicorn Kawaii", src: "../img/unicorn-kawaii.png" },
    { name: "Unicorn Love", src: "../img/unicorn-love.png" },
    { name: "Unicorn Rainbow", src: "../img/unicorn-rainbow.png" }
];
