const CACHE = "tot-play-v11";
const ASSETS = [
    "./",
    "index.html",
    "games/coloring.html",
    "games/abc-match.html",
    "games/number-match.html",
    "games/shape-match.html",
    "games/alphabet-trace.html",
    "games/silhouette-match.html",
    "games/pop-count.html",
    "games/peekaboo.html",
    "css/shared.css",
    "js/common.js",
    "js/sound-toggle.js",
    "js/page-init.js",
    "js/coloring.js",
    "js/coloring-data.js",
    "manifest.webmanifest",
    "icons/favicon.png",
    "icons/favicon.png",
    "icons/favicon.png",
    "img/clownfish.png",
    "img/turtle.png",
    "img/flower.png",
    "img/daisy.png",
    "img/lion-cub.png",
    "img/bear-cub.png",
    "img/lion.png",
    "img/fish.png",
    "img/sun.png",
    "img/cloud.png",
    "img/rainbow.png",
    "img/flower2.png",
    "img/butterfly.png",
    "img/car.png",
    "img/rocket.png",
    "img/cat.png",
    "img/tree.png",
    "img/apple.png",
    "img/star.png",
    "img/duck.png",
    "img/sailboat.png",
    "img/airplane.png",
    "img/ladybug.png",
    "img/ice-cream.png",
    "img/helicopter.png",
    "img/tractor.png",
    "img/horse.png",
    "img/horse-coloring.png",
    "img/seahorse-coloring.png",
    "img/sheeps-coloring.png",
    "img/cat-coloring.png",
    "img/dog-coloring.png",
    "img/elephant-coloring.png",
    "img/pig-coloring.png",
    "img/rabbit-coloring.png",
    "img/teddy-bears-coloring.png",
    "img/christmas-kittens.png",
    "img/christmas-santa-claus.png",
    "img/christmas-stockings.png",
    "img/christmas-teddy-bears.png",
    "img/christmas-tree.png",
    "img/merry-christmas.png",
    "img/muffin-coloring.png",
    "img/breakfast-coloring.png",
    "img/candies-coloring.png",
    "img/fruit-coloring.png",
    "img/ice-cream-coloring.png",
    "img/lollipop-coloring.png",
    "img/spaghetti-coloring.png",
    "img/sweets-coloring.png",
    "img/vegetable-coloring.png",
    "img/princess-glasses.png",
    "img/princess-beach.png",
    "img/princess-fox.png",
    "img/princess-coloring-1.png",
    "img/princess-coloring-2.png",
    "img/princess-moon.png",
    "img/princess-coloring-3.png",
    "img/princess-coloring-4.png",
    "img/princess-coloring-5.png",
    "img/airplane-coloring.png",
    "img/car-coloring.png",
    "img/helicopter-coloring.png",
    "img/ship-coloring.png",
    "img/train-coloring.png",
    "img/truck-coloring.png",
    "img/unicorn-birds.png",
    "img/unicorn-walking.png",
    "img/unicorn-flower.png",
    "img/unicorn-flying.png",
    "img/unicorn-friend.png",
    "img/unicorn-jumping.png",
    "img/unicorn-kawaii.png",
    "img/unicorn-love.png",
    "img/unicorn-rainbow.png",
    "img/silhouettes/dog.png",
    "img/silhouettes/octopus.png",
    "img/silhouettes/elephant.png",
    "img/silhouettes/bird.png",
    "img/silhouettes/aircraft.png",
    "img/silhouettes/dolphin.png",
    "img/silhouettes/fish.png",
    "img/silhouettes/starfish.png",
    "img/silhouettes/seahorse.png",
    "img/silhouettes/sealife.png",
    "img/silhouettes/dog-silhouette.png",
    "img/silhouettes/octopus-silhouette.png",
    "img/silhouettes/elephant-silhouette.png",
    "img/silhouettes/bird-silhouette.png",
    "img/silhouettes/aircraft-silhouette.png",
    "img/silhouettes/dolphin-silhouette.png",
    "img/silhouettes/fish-silhouette.png",
    "img/silhouettes/starfish-silhouette.png",
    "img/silhouettes/seahorse-silhouette.png",
    "img/silhouettes/sealife-silhouette.png"
];

self.addEventListener("install", e => {
    e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", e => {
    e.waitUntil(
        caches.keys()
            .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener("fetch", e => {
    if (e.request.method !== "GET") return;
    e.respondWith(
        caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
            const copy = res.clone();
            caches.open(CACHE).then(c => c.put(e.request, copy));
            return res;
        }).catch(() => caches.match("./")))
    );
});
